/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controlador.DireccionesTemp;
import Modelo.Cliente;
import Modelo.Direccion;
import Modelo.FacturaCabecera;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class VentanaEmergenteDirecciones extends javax.swing.JFrame {

    private Controlador.ControladorClientes cc;
    private FacturaCabecera fc;
    private Cliente cl;
    private DefaultTableModel direcciones;
    /**
     * Creates new form VentanaEmergenteDirecciones
     * @param tipo
     */
    
    int DireccionSelec;
    String dTipo;
    DefaultTableModel tabla;
    

    public VentanaEmergenteDirecciones( String tipo) {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    VentanaEmergenteDirecciones(Cliente cli) {

        
    }
    
    public void cargarModeloTabla(){
        
        ArrayList<Object> columna = new ArrayList<>();
        columna.add("Ciudad");
        columna.add("Calle Principal");
        columna.add("Calle Secundaria");
        
        for (Object columna1 : columna) {
           direcciones.addColumn(columna1);
        }
        //tablaDirecciones.setModel(direcciones);
        ArrayList<Object[]>  dir = new ArrayList<>(); 
        for (int i = 0; i < cl.getDirecciones().size(); i++) {
                Object[] d = new Object[]{cl.getDirecciones().get(i).getCiudad().getNombre(),cl.getDirecciones().get(i).getCallePrincipal(),
                                      cl.getDirecciones().get(i).getCalleSecundaria()};
                dir.add(d);
            
        }
        
        for (Object[] det : dir) {
            direcciones.addRow(det);
        }
        //this.tablaDirecciones.setModel(direcciones);
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        principal = new javax.swing.JTextField();
        secundaria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();

        jLabel7 = new javax.swing.JLabel();
        agregarCliente = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDirecciones = new javax.swing.JTable();
        btnUtilizarDireccionExistente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Direcciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingresar Calle Principal");


        principal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        principal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });

        secundaria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        secundaria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secundaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));


        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingresar Ciudad ");


        ciudad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ciudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));


        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ingresar Calle Secundaria");

        agregarCliente.setBackground(new java.awt.Color(0, 102, 255));
        agregarCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        agregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        agregarCliente.setText("Guardar Nueva Dirección");
        agregarCliente.setBorder(null);
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                    .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(secundaria)
                    .addComponent(ciudad))

                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(principal)

                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Buscar Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaDirecciones.setBackground(new java.awt.Color(0, 102, 204));
        tablaDirecciones.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tablaDirecciones.setForeground(new java.awt.Color(255, 255, 255));
        tablaDirecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ciudad", "Calle Principal", "Calle Secundaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDirecciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaDirecciones.setRowHeight(25);
        tablaDirecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDireccionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDirecciones);

        btnUtilizarDireccionExistente.setBackground(new java.awt.Color(0, 102, 255));
        btnUtilizarDireccionExistente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnUtilizarDireccionExistente.setForeground(new java.awt.Color(255, 255, 255));
        btnUtilizarDireccionExistente.setText("Utilizar esta Dirección");
        btnUtilizarDireccionExistente.setBorder(null);
        btnUtilizarDireccionExistente.setEnabled(false);
        btnUtilizarDireccionExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilizarDireccionExistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnUtilizarDireccionExistente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUtilizarDireccionExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalActionPerformed


    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        
        switch (dTipo){
            case "nuevo":

                String callep = principal.getText();
                String calles = secundaria.getText();
                String ciudades = ciudad.getText();
                
                if ((principal.getText().equals("")) || (secundaria.getText().equals(""))|| (ciudad.getText().equals(""))) {
                    JOptionPane.showMessageDialog(null,"Existen Campos Vacios");
                    
                }else {
                    
                    DireccionesTemp.addDirec(callep,calles,ciudades);
                    
                    tabla.addRow(new Object[]{ciudad,callep,calles}); 
                    
                }
        

                
                
                
                
                
            break;
    
        }   
        
        
        
        
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void agregarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCliente2ActionPerformed

//        int row= jTable1.getSelectedRow();
//        
//        Direccion pers=new Direccion();
//        
//        pers.setCiudadNombre((String) jTable1.getValueAt(row, 0));
//        pers.setCallePrincipal((String)jTable1.getValueAt(row, 1));
//        pers.setCalleSecundaria((String) jTable1.getValueAt(row, 2));
//        
//        DireccionesTemp.guardDir(pers);
//        
//        

    }//GEN-LAST:event_agregarCliente2ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablaDireccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDireccionesMouseClicked
//        btnUtilizarDireccionExistente.setEnabled(true);
//        int seleccion = tablaDirecciones.rowAtPoint(evt.getPoint());
//        String ciudad = String.valueOf(tablaDirecciones.getValueAt(seleccion, 1));
//        String callePrincipal = String.valueOf(tablaDirecciones.getValueAt(seleccion, 2));
//        String calleSecundaria = String.valueOf(tablaDirecciones.getValueAt(seleccion, 3));
//        
//        for (int i = 0; i < cl.getDirecciones().size(); i++) {
//            for (int j = 0; j < cl.getDirecciones().get(i).getCiudades().size(); j++) {
//                if (cl.getDirecciones().get(i).getCiudades().get(j).getNombre().equalsIgnoreCase(ciudad) == true) {
//                    Direccion auxD = cl.getDirecciones().get(i);
//                }
//            } 
//        }
//        
//        
    }//GEN-LAST:event_tablaDireccionesMouseClicked

    private void btnUtilizarDireccionExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilizarDireccionExistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUtilizarDireccionExistenteActionPerformed
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaEmergenteDirecciones(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCliente;
    private javax.swing.JButton btnUtilizarDireccionExistente;

    private javax.swing.JTextField ciudad;

    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTextField principal;
    private javax.swing.JTextField secundaria;
    private javax.swing.JTable tablaDirecciones;

    // End of variables declaration//GEN-END:variables
}
